version: "3.3"  # optional since v1.27.0
services:
 
  nginx:
    build: nginx/
    ports:
       - "81:80"
    networks:
      internal_routes:
        aliases:
          - nginx
 
  rabbitmq_create:
    image: rabbitmq  
    ports:
       - "5672:5672"
    networks:
      internal_routes:
        aliases:
          - rabbitmq

  mongodb_replicate_set_1:
    container_name: rs1
    image: mongo:4.2
    command: mongod --replSet RS --port 27041 --dbpath /data/db --config /resource/mongod.yml
    volumes:
      - ./mongodb/data/rs1:/data/db
      - ./mongodb/mongod.yml:/resource/mongod.yml
    ports:
      - "27020:27041"
    networks:
      internal_routes:
        aliases:
          - rs1

  mongodb_replicate_set_2:
    container_name: rs2
    image: mongo:4.2
    command: mongod --replSet RS --port 27042 --dbpath /data/db --config /resource/mongod.yml
    volumes:
      - ./mongodb/data/rs2:/data/db
      - ./mongodb/mongod.yml:/resource/mongod.yml
    ports:
      - "27018:27042"
    networks:
      internal_routes:
        aliases:
          - rs2


  mongodb_replicate_set_3:
    container_name: rs3
    image: mongo:4.2
    command: mongod --replSet RS --port 27043 --dbpath /data/db --config /resource/mongod.yml
    volumes:
      - ./mongodb/data/rs3:/data/db
      - ./mongodb/mongod.yml:/resource/mongod.yml
    ports:
      - "27019:27043"
    networks:
      internal_routes:
        aliases:
          - rs3


  user_list:
    build: list_user/
    volumes: 
       - ./list_user/:/app
    expose:
       - 5001
    networks:
      internal_routes:
        aliases:
          - user_list
   
  login:
    build: login/
    volumes: 
       - ./login/:/app
    expose:
       - 5002
    networks:
      internal_routes:
        aliases:
          - login       


  create_user:  
    build: create_user/
    volumes: 
       - ./create_user/:/app
    expose:
       - 5000
    networks:
      internal_routes:
        aliases:
          - create_user 
  
  data_subscriber:
    build: data_subscriber/
    volumes: 
      - ./data_subscriber/:/app
    restart: on-failure
    depends_on:
      - "rabbitmq_create"
    networks:
      internal_routes:

networks:
  internal_routes:      
